import { lazy } from 'react';
import {
  Activity,
  AppWindow,
  Box,
  Calculator,
  CalendarRange,
  ChartPie,
  CircleDashed,
  CirclePlus,
  FileDown,
  GalleryHorizontal,
  GitCommitHorizontal,
  Grid2x2,
  Hash,
  InfinityIcon,
  LayoutGrid,
  ListFilter,
  ListOrdered,
  Loader,
  LogOut,
  MousePointer2,
  Music,
  PanelLeft,
  Rotate3d,
  ScanLine,
  Search,
  Shapes,
} from 'lucide-react';
import type { Demo, DemoCategory } from './playground.types';

export const DEMO_CATEGORIES: DemoCategory[] = ['effects', 'tech', 'challenge'];

// 데모는 열 때만 받는다 — three·chart.js·jspdf 같은 무거운 의존성이 목록 화면에 실리지 않는다.
// 순서는 목록에 보이는 순서다.
export const demos: Demo[] = [
  // Effects
  {
    id: 'music',
    category: 'effects',
    icon: Music,
    tech: ['Audio API'],
    Component: lazy(() => import('../ui/demos/music')),
  },
  {
    id: 'hover',
    category: 'effects',
    icon: MousePointer2,
    tech: ['Hover Animation'],
    Component: lazy(() => import('../ui/demos/hover')),
  },
  {
    id: 'loading',
    category: 'effects',
    icon: Loader,
    tech: ['Loading Animation'],
    Component: lazy(() => import('../ui/demos/loading')),
  },
  {
    id: 'simple-motion',
    category: 'effects',
    icon: Shapes,
    tech: ['Animation'],
    Component: lazy(() => import('../ui/demos/simple-motion')),
  },
  {
    id: 'transform',
    category: 'effects',
    icon: Box,
    tech: ['3D Transform'],
    Component: lazy(() => import('../ui/demos/transform')),
  },
  {
    id: 'layout',
    category: 'effects',
    icon: LayoutGrid,
    tech: ['Layout Animation'],
    Component: lazy(() => import('../ui/demos/layout')),
  },
  {
    id: 'spring',
    category: 'effects',
    icon: Activity,
    tech: ['Spring Physics'],
    Component: lazy(() => import('../ui/demos/spring')),
  },
  {
    id: 'scroll-progress',
    category: 'effects',
    icon: CircleDashed,
    tech: ['Scroll Animation'],
    Component: lazy(() => import('../ui/demos/scroll-progress')),
  },
  {
    id: 'exit',
    category: 'effects',
    icon: LogOut,
    tech: ['AnimatePresence'],
    Component: lazy(() => import('../ui/demos/exit')),
  },
  {
    id: 'aos',
    category: 'effects',
    icon: ScanLine,
    tech: ['Scroll Animation'],
    Component: lazy(() => import('../ui/demos/aos')),
  },
  {
    id: 'modal',
    category: 'effects',
    icon: AppWindow,
    tech: ['Modal Animation'],
    Component: lazy(() => import('../ui/demos/modal')),
  },
  {
    id: 'timeline',
    category: 'effects',
    icon: GitCommitHorizontal,
    tech: ['Timeline Animation'],
    Component: lazy(() => import('../ui/demos/timeline')),
  },
  // Tech
  {
    id: 'data-visualization',
    category: 'tech',
    icon: ChartPie,
    tech: ['Chart.js', 'Data Visualization'],
    Component: lazy(() => import('../ui/demos/data-visualization')),
  },
  {
    id: 'pdf-download',
    category: 'tech',
    icon: FileDown,
    tech: ['PDF Download'],
    Component: lazy(() => import('../ui/demos/pdf-download')),
  },
  {
    id: 'carousel',
    category: 'tech',
    icon: GalleryHorizontal,
    tech: ['Carousel'],
    Component: lazy(() => import('../ui/demos/carousel')),
  },
  {
    id: 'pagination',
    category: 'tech',
    icon: ListOrdered,
    tech: ['Pagination'],
    Component: lazy(() => import('../ui/demos/pagination')),
  },
  {
    id: 'date-filter',
    category: 'tech',
    icon: CalendarRange,
    tech: ['Date Filter'],
    Component: lazy(() => import('../ui/demos/date-filter')),
  },
  {
    id: 'select-filter',
    category: 'tech',
    icon: ListFilter,
    tech: ['Select Filter'],
    Component: lazy(() => import('../ui/demos/select-filter')),
  },
  {
    id: 'input-filter',
    category: 'tech',
    icon: Search,
    tech: ['Input Filter'],
    Component: lazy(() => import('../ui/demos/input-filter')),
  },
  {
    id: 'sidebar',
    category: 'tech',
    icon: PanelLeft,
    tech: ['Sidebar'],
    Component: lazy(() => import('../ui/demos/sidebar')),
  },
  {
    id: 'infinite-scroll',
    category: 'tech',
    icon: InfinityIcon,
    tech: ['Infinite Scroll'],
    Component: lazy(() => import('../ui/demos/infinite-scroll')),
  },
  {
    id: 'floating-menu',
    category: 'tech',
    icon: CirclePlus,
    tech: ['Floating Menu'],
    Component: lazy(() => import('../ui/demos/floating-menu')),
  },
  // Challenge
  {
    id: 'three-viewer',
    category: 'challenge',
    icon: Rotate3d,
    tech: ['Three.js', '3D Animation'],
    Component: lazy(() => import('../ui/demos/three-viewer')),
  },
  {
    id: 'memory-game',
    category: 'challenge',
    icon: Grid2x2,
    tech: ['Game Logic', 'Animation'],
    Component: lazy(() => import('../ui/demos/memory-game')),
  },
  {
    id: 'tic-tac-toe',
    category: 'challenge',
    icon: Hash,
    tech: ['Game Logic', 'Grid System'],
    Component: lazy(() => import('../ui/demos/tic-tac-toe')),
  },
  {
    id: 'calculator',
    category: 'challenge',
    icon: Calculator,
    tech: ['Calculator', 'Animation'],
    Component: lazy(() => import('../ui/demos/calculator')),
  },
];

export function findDemo(id: string) {
  return demos.find((demo) => demo.id === id);
}
